server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobile_network_db  # Change to your DB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or 'create' if you want to drop and recreate tables
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true